debug:
  console: false
  players: false
tool:
  block: LAPIS_ORE
  item: BLAZE_ROD
  default-on: true
bucket:
  enabled: true
  safe: true
  place-safe: true
dispenser:
  enabled: true
  safe: true
  place-safe: true
region:
  maximum-volume: 1000
flow:
  maximum-depth: -1
logging:
  manual-flow: true
  region-flow: true
  natural-flow: false
