debug:
  console: false
  players: false
tool:
  block: LAPIS_ORE
  item: BLAZE_ROD
  default-on: true
bucket:
  enabled: true
  safe: true
  place-safe: true
dispenser:
  enabled: true
  safe: true
  place-safe: true
  whitelist: true
flow:
  maximum-volume: 1000
