debug:
  console: false
  players: false
tool:
  block: LAPIS_ORE
  item: BLAZE_ROD
bucket:
  enabled: true
  safe: true
  place-safe: true
dispenser:
  enabled: true
  safe: true
  place-safe: true
  whitelist: true
