name: SafeBuckets
main: nu.nerd.SafeBuckets.SafeBuckets
version: ${project.version}
description: ${project.description}
website: ${project.url}
database: true
authors: [Travis Watkins, Ed Kellett, Stephen McGregor]
